Pr5
pitt-software-practices/defects pull request #5
Opened 2020-10-29 14:16 UTC by meiirbek-islamov

2020-10-29 14:28 UTC, paulboone commented on .gitignore
> +defects.egg-info/PKG-INFO
*.egg-info

2020-10-29 14:29 UTC, paulboone commented on defects.egg-info/SOURCES.txt
> +defects.egg-info/top_level.txt
none of this should be added–this should be removed

2020-10-29 18:19 UTC, paulboone commented on .gitignore
> +*.egg-info
you need __pycache__ in here too. You accidentally committed a __pycache__file in the prior commit.

2020-10-29 18:21 UTC, paulboone requested changes
This is looking SO much better!! The only thing I see that still needs to be fixed is that you accidentally committed a __pycache__ file that should be removed. See my other comment.

2020-10-29 23:22 UTC, paulboone approved these changes
You got some great practice rebasing with this PR! It looks good. At some point, if it makes sense, you should go back and clean up Introduce_Defects.py (filename should definitely not have caps, for starters!), but I know we were just trying to get it into git at this point. I'm going to merge it.

2020-10-29 23:28 UTC, paulboone commented
Ok, so one more problem! You actually rebased back into the master commit history (which you should never do), so now we have a merge conflict merging into master. We can manually resolve the conflicts and then merge. It will be a little ugly, but it is OK for your first PR. Just make sure that you don't rebase too far back next time. Probably easiest to fix it up over a zoom call so we can move on to the next PR...? I want you to continue doing new work rather than working on this one too much more.

2020-10-30 14:14 UTC, meiirbek-islamov commented
Hi paul, 

Yeah, this was a great rebasing practice for me. I can meet today over zoom to quickly resolve conflicts and continue working further. I already finished working this defect project but I haven't PR'd yet. They are in another branch. I would like to merge them and start search and replace project immediately. I already created a repo and setup.py for that project. I called it functionaliseMOF. If we meet today I would like to discuss also the details of that project too.

2020-10-30 20:02 UTC, merged